typography_spectrum: 0.5012
color:
  brandColors:
    - '#ffffff'
    - '#134880'
    - '#babac0'
    - '#8c898f'
    - '#d7d7d9'
  brandStrength: 0.8125
  lightness: 0.02395854890346527
  saturation: 0.9701840977650136
  rhythmicContrast: 0.9060470419935882
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.92267
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6311e341-2277-4bc5-bac4-101b5c0cd0a7.jpg
name: bodyarmourcanada.com
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6f5ac24-2b0b-44a2-b72c-9defab421e4c.jpg
title: Body Armour Canada
purpose: []
