name: bodyarmourcanada.com
favicon: null
layout_spectrum: 0.46271403366699815
typography_spectrum: 0.05646836757659912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7772810249589384
  lightness: 0.02395854890346527
  saturation: 0.9701840977650136
  rhythmicContrast: 0.9060470419935882
purpose: []
